# Build offler's examples.
#
#   make          every example: two browser bundles and a native binary each
#   make web      just the bundles; then open shapes.html etc.
#   make native   just the binaries
#   make lib      type-check and build the library alone (offler.ipkg)
#   make check    the programs that must fail to compile
#   make clean
#
# The shader embedding is an ordinary rule with ordinary prerequisites rather
# than an .ipkg prebuild hook: a hook runs on every build whether or not a
# shader changed, and cannot put Offler/Shaders.idr in the module list,
# because Idris resolves that list before the hook fires.

IDRIS  ?= idris2
CC     ?= cc

# Run-time bounds tests in the batch draw path: `checked` (the default) or
# `trusted`. The flag becomes the generated Offler.Gfx.Config module, so a
# change here recompiles exactly what depends on it.
BOUNDS ?= checked
ifeq ($(BOUNDS),trusted)
  BOUNDS_CTOR := Trusted
else
  BOUNDS_CTOR := Checked
endif

EXEC    := build/exec
SHADERS := shaders/standard.vert shaders/standard.frag shaders/standard.wgsl \
           shaders/standard-line.vert shaders/standard-inst.vert \
           shaders/lines.vert shaders/lines.frag shaders/lines.wgsl
ASSETS  := assets/uv-checker.png assets/marble.jpg assets/cutout.png
GENERATED := Offler/Shaders.idr Offler/Gfx/Config.idr Examples/Assets.idr
SOURCES := $(filter-out $(GENERATED),$(wildcard Offler/*.idr Offler/Gfx/*.idr Offler/Web/*.idr Offler/Native/*.idr) \
                                     $(wildcard Examples/*.idr Examples/*/*.idr))

# name (bundle/binary) -> module directory
EXAMPLES := shapes lines swarm flat2d custom chime
dir_shapes := Shapes
dir_lines  := Lines
dir_swarm  := Swarm
dir_flat2d := Flat2d
dir_custom := Custom
dir_chime  := Chime

BUNDLES  := $(foreach e,$(EXAMPLES),$(EXEC)/$(e)-gl2.js $(EXEC)/$(e)-gpu.js)
NATIVES  := $(foreach e,$(EXAMPLES),$(EXEC)/$(e))
SHIMS    := $(foreach e,$(EXAMPLES),$(EXEC)/$(e)_app/liboffler.so)

.PHONY: all web native lib run-% check clean
.DEFAULT_GOAL := all

all: web native

web: $(BUNDLES)
	@echo "open shapes.html, lines.html, swarm.html, flat2d.html, custom.html or chime.html -- no server needed"

native: $(NATIVES) $(SHIMS)
	@echo "built $(NATIVES) -- run them directly, no environment needed"

run-%: $(EXEC)/% $(EXEC)/%_app/liboffler.so
	./$(EXEC)/$*

lib: Offler/Shaders.idr Offler/Gfx/Config.idr
	$(IDRIS) --build offler.ipkg

# A guarantee is only worth anything if the programs it is supposed to reject
# actually fail to compile. Each of these must not build, and must not build
# for the stated reason -- a test that fails because of a typo in its imports
# passes just as quietly otherwise.
#
# The stack check is the other kind of guarantee: a program that must *run*,
# at exactly the object cap, on the backend where the stack is scarcest --
# plus a grep of the generated output for the trampoline it depends on,
# because whether a loop got `__tailRec` is visible nowhere in the source.
check: stackcheck
	@fail=0; for t in Tests/*.idr; do \
	  want=$$(sed -n 's/^-- expect: //p' "$$t" | head -1); \
	  if [ -z "$$want" ]; then \
	    echo "FAIL  $$t has no '-- expect:' line"; fail=1; continue; \
	  fi; \
	  err=$$($(IDRIS) -p linear -p base --check "$$t" 2>&1); \
	  if [ $$? -eq 0 ]; then \
	    echo "FAIL  $$t compiled, but it must not"; fail=1; \
	  elif ! echo "$$err" | grep -qF "$$want"; then \
	    echo "FAIL  $$t was rejected, but not for '$$want':"; \
	    echo "$$err" | grep -m1 "^Error"; fail=1; \
	  else \
	    echo "ok    $$t rejected: $$want"; \
	  fi; \
	done; exit $$fail

.PHONY: stackcheck
stackcheck: Offler/Shaders.idr Offler/Gfx/Config.idr
	@$(IDRIS) -p linear --cg node -o stackcheck Checks/StackCheck.idr > /dev/null
	@out=$$(node $(EXEC)/stackcheck); \
	  if [ "$$out" != "filled 10240 of 10240" ]; then \
	    echo "FAIL  StackCheck said '$$out'"; exit 1; \
	  else echo "ok    Checks/StackCheck.idr: $$out"; fi
	@if sed -n '/^function Offler_Gfx_Uniform_go/,/^}/p' $(EXEC)/stackcheck \
	     | grep -q __tailRec; \
	  then echo "ok    pokeObjects loop is trampolined (__tailRec)"; \
	  else echo "FAIL  pokeObjects loop lost its trampoline"; exit 1; fi

clean:
	rm -rf build $(GENERATED)

# ---------------------------------------------------------------- config

# Regenerated on every run but only *touched* when the content changes, so
# flipping BOUNDS rebuilds and an unchanged value does not.
Offler/Gfx/Config.idr: FORCE
	@printf '||| Generated by the Makefile -- do not edit. `make BOUNDS=trusted`\n||| turns the batch bounds tests off; the default is checked.\nmodule Offler.Gfx.Config\n\nimport Offler.Gfx.Array\n\npublic export\nboundsMode : Bounds\nboundsMode = %s\n' "$(BOUNDS_CTOR)" > $@.tmp
	@if cmp -s $@.tmp $@; then rm $@.tmp; else mv $@.tmp $@; echo "generated $@ (boundsMode = $(BOUNDS_CTOR))"; fi

FORCE:

# --------------------------------------------------------------------- shaders

# The shaders live in shaders/ as real .vert/.frag/.wgsl files, but they are
# embedded at build time rather than fetched at run time. Browsers block
# fetch() on file:// origins, and embedding means a page works when opened
# straight off disk as well as over a server. The native build embeds them
# for the same reason a binary should not need its assets beside it.
#
# Idris multiline strings need no escaping here: the shaders contain no
# backslash (which would start an escape or a \{ interpolation) and no """.
Offler/Shaders.idr: $(SHADERS) Makefile
	@printf '||| Generated by the Makefile from shaders/ -- do not edit.\nmodule Offler.Shaders\n' > $@
	@set -e; for pair in vertSrc:standard.vert fragSrc:standard.frag wgslSrc:standard.wgsl \
	                     lineStdVertSrc:standard-line.vert instStdVertSrc:standard-inst.vert \
	                     lineVertSrc:lines.vert lineFragSrc:lines.frag lineWgslSrc:lines.wgsl; do \
	  name=$${pair%%:*}; \
	  printf '\nexport\n%s : String\n%s = """\n' "$$name" "$$name" >> $@; \
	  cat "shaders/$${pair#*:}" >> $@; \
	  printf '"""\n' >> $@; \
	done
	@echo "generated $@"

# --------------------------------------------------------------------- assets

# Test images embedded as base64, so the browser pages keep working when
# opened straight off disk: file:// origins taint image loads into WebGL,
# and fetch() is blocked outright, but data: URLs are same-origin. The
# native build decodes the same strings through stb_image, so a binary
# needs no assets beside it either.
Examples/Assets.idr: $(ASSETS) Makefile
	@printf '||| Generated by the Makefile from assets/ -- do not edit.\nmodule Examples.Assets\n' > $@
	@set -e; for triple in uvCheckerPng:image/png:uv-checker.png marbleJpg:image/jpeg:marble.jpg cutoutPng:image/png:cutout.png; do \
	  name=$${triple%%:*}; rest=$${triple#*:}; mime=$${rest%%:*}; file=$${rest#*:}; \
	  printf '\n||| %s, base64.\nexport\n%s : String\n%s = "' "$$file" "$$name" "$$name" >> $@; \
	  base64 -w0 "assets/$$file" >> $@; \
	  printf '"\n\nexport\n%sMime : String\n%sMime = "%s"\n' "$$name" "$$name" "$$mime" >> $@; \
	done
	@echo "generated $@"

# ------------------------------------------------------------------- compiling

# One compilation per browser backend per example. Neither bundle contains
# the other's code, so the renderer is monomorphic and each page picks its
# bundle by URL.
define EXAMPLE_template
$(EXEC)/$(1)-gl2.js: Offler/Shaders.idr Offler/Gfx/Config.idr Examples/Assets.idr $(SOURCES)
	$(IDRIS) -p linear --cg javascript -o $(1)-gl2.js Examples/$(2)/MainGl2.idr
	@test -f $$@ || { echo "$$@ was not produced" >&2; exit 1; }
	@echo "built $$@ ($$$$(wc -c < $$@) bytes)"

$(EXEC)/$(1)-gpu.js: Offler/Shaders.idr Offler/Gfx/Config.idr Examples/Assets.idr $(SOURCES)
	$(IDRIS) -p linear --cg javascript -o $(1)-gpu.js Examples/$(2)/MainGpu.idr
	@test -f $$@ || { echo "$$@ was not produced" >&2; exit 1; }
	@echo "built $$@ ($$$$(wc -c < $$@) bytes)"

$(EXEC)/$(1): Offler/Shaders.idr Offler/Gfx/Config.idr Examples/Assets.idr $(SOURCES)
	$(IDRIS) -p linear --cg chez -o $(1) Examples/$(2)/Main.idr
	@test -f $$@ || { echo "$$@ was not produced" >&2; exit 1; }

# Chez dlopens liboffler.so by bare name, so it has to be somewhere the
# dynamic loader looks. Idris's generated launcher already puts <exe>_app/ on
# LD_LIBRARY_PATH for libidris2_support.so, so dropping the shim in beside it
# means the binary needs no environment set to run. That directory is
# Idris's, which is why this depends on the binary rather than merely on the
# C: a rebuilt executable gets a rebuilt app dir to sit in.
$(EXEC)/$(1)_app/liboffler.so: build/liboffler.so $(EXEC)/$(1)
	@mkdir -p $$(@D)
	cp build/liboffler.so $$@
endef

$(foreach e,$(EXAMPLES),$(eval $(call EXAMPLE_template,$(e),$(dir_$(e)))))

# ------------------------------------------------------------------- the shim

# SDL3 ships a pkg-config file; wgpu-native does not, and nixpkgs splits its
# headers into a separate output from the .so. Hence one discovered and one
# supplied. `nix develop` sets all four, so neither needs setting by hand
# there.
ifeq ($(strip $(SDL_CFLAGS)$(SDL_LIBS)),)
  ifneq ($(strip $(shell pkg-config --exists sdl3 2>/dev/null && echo yes)),)
    SDL_CFLAGS := $(shell pkg-config --cflags sdl3)
    SDL_LIBS   := $(shell pkg-config --libs sdl3)
  else ifneq ($(strip $(SDL3_PREFIX)),)
    SDL_CFLAGS := -I$(SDL3_PREFIX)/include
    SDL_LIBS   := -L$(SDL3_PREFIX)/lib -lSDL3 -Wl,-rpath,$(SDL3_PREFIX)/lib
  endif
endif

ifeq ($(strip $(WGPU_CFLAGS)$(WGPU_LIBS)),)
  ifneq ($(strip $(WGPU_PREFIX)),)
    WGPU_CFLAGS := -I$(WGPU_PREFIX)/include
    WGPU_LIBS   := -L$(WGPU_PREFIX)/lib -lwgpu_native -Wl,-rpath,$(WGPU_PREFIX)/lib
  endif
endif

build/liboffler.so: csrc/offler_native.c csrc/offler_audio.c Makefile
	@test -n "$(strip $(SDL_LIBS))" \
	  || { echo "no SDL3: install it, set SDL3_PREFIX, or use 'nix develop'" >&2; exit 1; }
	@test -n "$(strip $(WGPU_LIBS))" \
	  || { echo "no wgpu-native: set WGPU_PREFIX, or use 'nix develop'" >&2; exit 1; }
	@test -n "$(strip $(STB_CFLAGS))" \
	  || { echo "no stb: set STB_CFLAGS to point at stb_image.h, or use 'nix develop'" >&2; exit 1; }
	@mkdir -p $(@D)
	$(CC) -O2 -fPIC -shared -o $@ $(filter %.c,$^) \
	  $(SDL_CFLAGS) $(WGPU_CFLAGS) $(STB_CFLAGS) $(SDL_LIBS) $(WGPU_LIBS)
	@echo "built $@"
